---
driver_plugin: vagrant
platforms:
- name: squeeze-6.0.6
  driver_config:
    box: squeeze-6.0.6 
  attributes:
    lsb:
      codename:
        squeeze
- name: wheezy-7.0.0
  driver_config:
    box: wheezy-7.0.0
- name: centos-6.3
  driver_config:
    box: centos-6.3
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-6.3.box
suites:
- name: default
  run_list:
  - recipe[up2date]
  - recipe[watchdog]
  - recipe[watchdog::_test_lwrp]
  - recipe[minitest-handler]
  attributes: {}
